version: '3.7'
services:
  api:
    container_name: api
    build:
      dockerfile: Dockerfile
      context: ./services/api
    ports:
      - 8000:5000
    volumes:
      - ./services/api:/usr/src/app
      - ./assets:/mnt
    env_file: ./.env
    depends_on:
      - database
      - rabbit-mq
    networks:
      - internal

  converter:
    container_name: converter
    build:
      dockerfile: Dockerfile
      context: ./services/converter
    volumes:
      - ./services/converter:/usr/src/app
      - ./assets:/mnt
    env_file: ./.env
    depends_on:
      - database
      - rabbit-mq
    networks:
      - internal
  
  rabbit-mq:
    image: rabbitmq:3-management
    container_name: rabbit-mq
    ports:
        # Management port
        - 15672:15672
    env_file: ./.env
    volumes:
      - ./rabbit-mq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    networks:
      - internal

  database:
    container_name: database
    image: postgres:15
    restart: always
    # Uses the variables starting with POSTGRES_
    ports:
      - 5430:5432
    env_file: ./.env
    volumes:
      - database-data:/var/lib/postgresql/data
    networks:
      - internal

volumes:
  rabbit-mq-data:
  database-data:


networks:
  internal:
