version: '3.7'
services:
  database:
    container_name: database
    image: postgres:15
    restart: always
    ports:
      - 5432:5432
    env_file: ./.env
    volumes:
      - database-data:/var/lib/postgresql/data

volumes:
  database-data:
