version: '3.7'
services:
  
  rabbit-mq:
    image: rabbitmq:3-management
    container_name: rabbit-mq
    ports:
        - 80:15672
        - 5672:5672
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    env_file: ../.env
    restart: always

volumes:
  rabbit-mq-data:
